#!/usr/bin/env sh
# Writes infra/.env with random passwords and signing keys for docker compose.
#
#   ./init-env.sh lan                  test on your own network: plain HTTP on port 8080, dev login on
#   ./init-env.sh prod api.example.com a server with a domain: HTTPS, dev login off
#
# Needs a POSIX shell and openssl (on Windows, run it from Git Bash or WSL). It never overwrites an
# existing .env: delete that first to start over (which also signs everyone out).
set -eu

cd "$(dirname "$0")"
mode=${1:-}
domain=${2:-}

usage() {
	sed -n '2,8p' "$0" | sed 's/^# \{0,1\}//' >&2
	exit 2
}

case "$mode" in
lan) ;;
prod) [ -n "$domain" ] || usage ;;
*) usage ;;
esac

if [ -e .env ]; then
	echo "infra/.env already exists; not touching it." >&2
	exit 1
fi
command -v openssl >/dev/null 2>&1 || {
	echo "openssl is required." >&2
	exit 1
}

umask 077
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

openssl genpkey -algorithm ed25519 -out "$tmp/jwt.pem" 2>/dev/null
openssl pkey -in "$tmp/jwt.pem" -pubout -out "$tmp/jwt.pub" 2>/dev/null

# PEM files on one line with literal \n separators; the backend turns them back into newlines.
one_line() {
	awk 'BEGIN { ORS = "\\n" } { print }' "$1" | sed 's/\\n$//'
}

if [ "$mode" = lan ]; then
	app_env=dev
	dev_login=true
	site=":80"
	http_port=8080
else
	app_env=prod
	dev_login=false
	site=$domain
	http_port=80
fi

cat >.env <<EOF
# Generated by init-env.sh ($mode) on $(date -u +%Y-%m-%d). Keep it private and never commit it.

# dev (LAN testing) or prod.
APP_ENV=$app_env
# Lets the debug app sign in without Google, as any email. Only for testing on your own network;
# the backend refuses to start in prod with it on.
APP_DEV_LOGIN_ENABLED=$dev_login

# Where Caddy listens: ":80" for plain HTTP, or your domain for automatic HTTPS.
SITE_ADDRESS=$site
HTTP_PORT=$http_port
HTTPS_PORT=443

# Google OAuth client id(s) accepted for sign-in (comma-separated). Needed for Google Sign-In.
APP_GOOGLE_CLIENT_IDS=

# Database and Redis passwords (only reachable inside the compose network).
POSTGRES_PASSWORD=$(openssl rand -hex 24)
REDIS_PASSWORD=$(openssl rand -hex 24)

# Access-token signing key (Ed25519). Replacing it only makes apps fetch a new access token.
APP_JWT_KEY_ID=$(date -u +%Y-%m)-$(openssl rand -hex 3)
APP_JWT_PRIVATE_KEY='$(one_line "$tmp/jwt.pem")'
APP_JWT_PUBLIC_KEY='$(one_line "$tmp/jwt.pub")'

# Encrypts refresh tokens kept briefly for crash retries (32 random bytes, base64).
APP_REFRESH_GRACE_KEY=$(openssl rand -base64 32)

# Optional: space-separated IPs or CIDRs allowed to open /admin (default: anywhere).
# ADMIN_ALLOW_IPS="203.0.113.7/32 198.51.100.0/24"
EOF

echo "Wrote infra/.env ($mode). Next: docker compose up -d --build"
